name: base image and version test
on:
  push:
    branches: base-ope-image
jobs:
  image_version_check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas jq
      - name: make build # makes the container image build 
        run: |
          make build
      - name: get base image and version
        run: |
          docker run -d --name stable quay.io/rh_ee_keli/ucsls:stable-base-ope-latest 
          ID=$( docker ps -aqf "name=stable" )     
          docker inspect quay.io/rh_ee_keli/ucsls:stable-base-ope-latest > image.json
          cat image.json
          #VERSION2=$(docker inspect --format={{index .Config.Labels "version"}} myimage:latest)
          IMAGE_ID=$( docker images --format "{{.ID}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          docker container ls --all --filter=ancestor=$ID --format "{{.ID}}"
          VERSION=$(jq -r '.[0].Config.Labels["version"]' image.json)
          BASE_IMAGE=$(jq -r '.[0].Config.Image' image.json)
          BASE_IMAGE2=$(docker history --no-trunc quay.io/rh_ee_keli/ucsls:stable-base-ope-latest | grep -v '<missing>' | tail -1 | awk '{print $5}')
          echo "Version: $VERSION   $VERSION2"
          echo "Base image: $BASE_IMAGE    $BASE_IMAGE2"
