name: health check
on:
  push:
    branches: base-ope-image
jobs:
  health-check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: make build # makes the container image build 
        run: |
          make build
      - name: check health #runs image and checks if it is up running after 12 seconds 
        run: |
          IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          docker run -d --name stable $IMAGE 
          sleep 12 #sleep for 7s to see if image starts properly
          CONTAINER_NAME="stable"
          HEALTH=$(docker ps --format "{{.Names}}: {{.Status}}" | grep "$CONTAINER_NAME" | awk '{print $2}')
          docker ps -a
          echo ""
          if [[ "$HEALTH" == "Up" ]]; then
          echo "HEALTHY : container is up and running"
          else
          echo "ERROR : container is not running"
          exit -1
          fi
          echo ""
          docker stop stable
