name: jup-nb-test
on:
  push:
    branches: base-ope-image #might need to change to be test-book
jobs:
  jup-nb:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas ipywidgets notebook
          #PY=$( cat .github/workflows/import_test.py ) 
          #$PY | while read line
          #do 
          #      $line >> ./test.py
          #done 
          cp .github/workflows/import_test.ipynb ./test.ipynb
          cp .github/workflows/import_test.py ./test_sc.py    
          cp .github/workflows/stop.ipynb ./stop.ipynb
          #Y >> ./test.py
      - name: make build # makes the container image build 
        run: |
          make build
      - name: check health #runs image and checks if it is up running after 12 seconds 
        run: |
          IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          echo "running"
          docker run -d --name stable $IMAGE #jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
          echo "done running"
          #.github/workflows/test_script.sh #run the container and run the shell script, this might need to be a path within the github workflow file
        
          sleep 10
          #LINK=file:///home/jovyan/.local/share/jupyter/runtime/jpserver-7-open.html
          
          #echo "with loop" 
          
          #cat ./test.py

          echo "cp"

          cat ./test_sc.py
          cat ./stop.ipynb
          cat ./test.ipynb
          cat ./stop.ipynb 
          #docker ps -a  
          
          chmod +x ./test_sc.py
          chmod +x ./test.ipynb
          chmod +x ./stop.ipynb
          TEST=$( ./test_sc.py)

          TEST2=$( ./test.ipynb)
          TEST3=$( ./stop.ipynb)
          #
          #docker ps -a
          ##docker exec stable pwd
          #docker exec stable ls
          #docker exec stable python $TEST
          echo "exec and run"
          docker exec stable python $TEST #$TEST3
          #HOST_PORT=$(docker port stable 8888/tcp | cut -d':' -f2)
           
          echo "quitting"
          #HOST_PORT=$(docker port stable 8888/tcp | cut -d':' -f2)
          # docker exec stable stop
          #docker exec stable jupyter notebook stop
          
          #had python before path
          # echo "image py" 
          #docker exec -it $IMAGE .github/workflows/import_test.py
          #echo "image sh"
          #docker exec -it $IMAGE .github/workflows/test_script.sh
          #echo "from scripts folder in container"

          #docker exec stable python import_test.py 
          
          #echo "container py"
          #docker exec stable python $TEST
          #echo "container sh"
          #docker exec stable .github/workflows/test_script.sh

          docker stop stable
