name: RISE check
on:
  push:
    branches: base-ope-image
jobs:
  checksum:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
          npm install cypress
      - name: pull image
        run: |
          IMAGE=quay.io/rh_ee_keli/ope:image-template-NERC-test
          docker pull $IMAGE
          docker image ls 
      - name: run
        run: |
          IMAGE=quay.io/rh_ee_keli/ope:image-template-NERC-test
          docker run -d --name stable $IMAGE
