name: RISE check
on:
  push:
    branches: base-ope-image
jobs:
  rise-check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
          npm install cypress
          cp .github/workflows/test.spec.js ./test.spec.js
      - name: pull image
        run: |
          #IMAGE=quay.io/rh_ee_keli/ope:image-template-NERC-test
          IMAGE=cypress/base:ubuntu18-node12.14.1
          docker pull $IMAGE
          docker image ls 
      - name: run
        run: |
          #IMAGE=quay.io/rh_ee_keli/ope:image-template-NERC-test
          IMAGE=cypress/base:ubuntu19-node12.14.1
          docker image ls
          docker run --cypress stable $IMAGE
          docker ps -a 
          docker logs cypress
          echo "sleeping"
          sleep 15
          docker ps -a
          cat ./test.spec.js
          docker exec cypress ./test.spec.js
          sleep 5
          docker ps -a
          #- name: run cypress test
          #uses: docker/cli-action@v2
          #with:
          #image: cypress/base:ubuntu18-node12.14.1
          #entrypoint: ["cypress", "run", "--spec", "./test.spec.js"]
          #docker stop stable






