name: time and size 
on:
  push:
    branches: base-ope-image
jobs:
  time_and_size:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: make build and calculate elapsed time # makes the container image build and then creates var with checksum value to be compared 
        run: |
          start=$(date +%s)
          time make build --silent
          end=$(date +%s)
          seconds=$((end-start))
          elapsed=$(echo "scale=2; ($end - $start) / 60.0" | bc)
          #sec_2_min=$(($elapsed/60.0))
          #echo "sec to min = $sec_2_min"
          min=${elapsed%.*}
          echo "min = $min"
          sec_cut=${elapsed#*.}
          sec_round="${sec_cut:0:1}.${sec_cut:1}"
          echo "sec cut = $sec_cut" 
          echo "sec round = $sec_round"
          sec=$( echo "$sec_round * 6" | bc -l)

          echo "BUILD TIME:  $min MIN $sec SECS  or  $seconds seconds" > ./time.txt

      - name: extract size and display time and size
        run: |
          IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          docker run -d --name stable $IMAGE 
          docker ps -a
          SIZE=$( docker images --format "{{.Size}}" $IMAGE )
          echo ""
          echo ""
          cat ./time.txt
          #echo "BUILD TIME:  $min MIN $sec SECS  or  $seconds seconds"
          echo "" 
          echo "IMAGE SIZE:  $SIZE"
          echo ""
          echo ""
          docker stop stable
                
