name: time and size 
on:
  push:
    branches: base-ope-image
jobs:
  time_and_size:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: make build and calculate elapsed time # makes the container image build and then creates var with checksum value to be compared 
        run: |
          start=$(date +%s)
          time make build
          end=$(date +%s)
          echo "end= $end  start= $start"
          elapsed=$((end-start))
          min=$elapsed/60
          min_cut=${elapsed%.*} #this assumes single digits thoooo
          sec_cut=${elapsed#*.}
          sec=$((sec_cut * 60))

      - name: extract size
        run: |
          docker run -d --name stable quay.io/rh_ee_keli/ucsls:stable-base-ope-latest 
          docker ps -a
          #IMAGE_ID=$( docker images --format "{{.ID}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          SIZE=$( docker images --format "{{.Size}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          echo "" 
          echo "BUILD TIME:  $min MIN $sec SECS  $elapsed seconds"
          echo "" 
          echo "IMAGE SIZE:  $SIZE"
          echo ""
          docker stop stable
                
