name: time and size 
on:
  push:
    branches: base-ope-image
jobs:
  time_and_size:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: time make build # makes the container image build and then creates var with checksum value to be compared 
        run: |
          time make build >> build.txt
      - name: get the size #creates var with checksum value to be compared 
        run: |
          #docker image ls
          #docker images quay.io/rh_ee_keli/ucsls
          #docker ps -a 
          echo "RUN CONTAINER"
          docker run -d --name stable quay.io/rh_ee_keli/ucsls:stable-base-ope-latest 
          echo "LIST RUNNING CONTAINERS"
          docker ps -a

          IMAGE_ID=$( docker images --format "{{.ID}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          echo "image id =  $IMAGE_ID"
          SZE=$( docker images --format "{{.Size}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          echo "SZE = $SZE"
          #docker stop stable
          # docker container inspect quay.io/rh_ee_keli/ucsls:stable-base-ope-latest

          #TIME=$( docker history --format "{{.CreatedAt}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest | tail -1 | xargs -I % sh -c 'echo $(( $(date -u -d % +%s) - $(date -u -d "$(docker history --format "{{.CreatedAt}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest | head -2 | tail -1)" +%s) )) seconds' )
                
          echo "time = $TIME"
          START=$(docker inspect --format "{{.State.StartedAt}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest)
          STOP=$(docker inspect --format "{{.State.FinishedAt}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest) 
          echo $START
          echo $STOP
          START_TIMESTAMP=$(date --date=$START +%s)
          STOP_TIMESTAMP=$(date --date=$STOP +%s)
          echo $START_TIMESTAMP
          echo $STOP_TIMESTAMP
          echo $(($STOP_TIMESTAMP-$START_TIMESTAMP)) seconds

          docker stop stable

          TIME=$( cat build.txt ) 

          T=$(echo $TIME | grep "real* ")

          echo $T
