name: time and size 
on:
  push:
    branches: base-ope-image
jobs:
  checksum:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: time make build # makes the container image build and then creates var with checksum value to be compared 
        run: |
          time make build
      - name: get the size #creates var with checksum value to be compared 
        run: |
          docker image ls
          docker container inspect quay.io/rh_ee_keli/ucsls:table-base-ope-latest

          START=$(docker inspect --format='{{.State.StartedAt}}' stable-base-ope-latest)
          STOP=$(docker inspect --format='{{.State.FinishedAt}}' stable-base-ope-latest) 
          echo $START
          echo $STOP
          START_TIMESTAMP=$(date --date=$START +%s)
          STOP_TIMESTAMP=$(date --date=$STOP +%s)
          echo $START_TIMESTAMP
          echo $STOP_TIMESTAMP
          echo $(($STOP_TIMESTAMP-$START_TIMESTAMP)) seconds
