name: time and size 
on:
  push:
    branches: base-ope-image
jobs:
  time_and_size:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: time make build # makes the container image build and then creates var with checksum value to be compared 
        run: |
          # Run the "time make build" command and capture the output
          output=$(time make build 2> build.txt)
          cat ./build.txt
          echo $output
          
          # # Extract the elapsed time value from the output
          BUILD_TIME=$(echo "$output" | grep "real" | awk '{print $2}')
          #
          # # Print the elapsed time value
          echo "Build time: $BUILD_TIME seconds"
          
          #output2=$(time make build 2>&1)
          #BUILD_TIME3=$(echo "$output2" | grep "real" | awk '{print $2}')
          #echo "Build time $BUILD_TIME3 seconds"

      - name: get size
        run: |
          #docker image ls
          #docker images quay.io/rh_ee_keli/ucsls
          #docker ps -a 
          echo "RUN CONTAINER"
          docker run -d --name stable quay.io/rh_ee_keli/ucsls:stable-base-ope-latest 
          echo "LIST RUNNING CONTAINERS"
          docker ps -a
          IMAGE_ID=$( docker images --format "{{.ID}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          echo "image id =  $IMAGE_ID"
          SZE=$( docker images --format "{{.Size}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest )
          echo "SZE = $SZE"

          SZ=$( docker inspect --size stable)

          echo "SZ= $SZ"

          #TIME=$( docker history --format "{{.CreatedAt}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest | tail -1 | xargs -I % sh -c 'echo $(( $(date -u -d % +%s) - $(date -u -d "$(docker history --format "{{.CreatedAt}}" quay.io/rh_ee_keli/ucsls:stable-base-ope-latest | head -2 | tail -1)" +%s) )) seconds' )
                
          docker stop stable
                
