name: time and size 
on:
  push:
    branches: base-ope-image
jobs:
  checksum:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas
      - name: time make build # makes the container image build and then creates var with checksum value to be compared 
        run: |
          time make build
      - name: run checksum #creates var with checksum value to be compared 
        run: |
          docker image ls -s	
